### ISSUE TITLE
Add support for volume persistence in dockerfile

### ISSUE THREAD

**Issue by ravensorb** [structr/structr#531]
It would be great if there was a volume (or set of volumes) that are defined in the default dockerfile to allow for us to use for persistence of data.  Right now, the only option is to create a custom docker file based on the default one, setup the volumes, and either "move" or "link" folders to the volumes.  This could cause issues going forward with upgrades if anything changes.

Possible suggestions:
- Volume for each individual "folder" that contains data that is unique to an install (data, db, files, logs, sessions)
- One volume that contains ALL files that are unique to an instance (note: this should contain seed.zip, structr.conf, etc)

**Comment by ravensorb** [comment]
Just checking in on this - am I missing some thing and is there another way to persist the data between versions?

**Comment by drugz** [comment]
You can also take out both whole folders and individual files. 
Try playing with this docker-compose.yml

```
version: "3.7"

services:
  backend:
    image: structr/structr:latest
    container_name: structr
    restart: unless-stopped
    depends_on:
      - neo4j
    volumes:
      # - ./structr:/structr
      - ./structr/structr.conf:/var/lib/structr/structr.conf
      - ./structr/db:/var/lib/structr/db
      - ./structr/files:/var/lib/structr/files
      - ./structr/snapshots:/var/lib/structr/snapshots
    ports:
      - 8082:8082
      - 8083:8083

  neo4j:
    container_name: ${DOCKER_IMAGE_NEOJ}
    image: neo4j:3.5
    restart: unless-stopped
    hostname: neo4j
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/conf:/conf
      - ./neo4j/import:/import
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
      - ./neo4j/certificates:/certificates
      - ./neo4j/run:/run
    build:
      context: ./neo4j
      dockerfile: Dockerfile

volumes:
  data:
  logs:
  conf:
  plugins:
  backups:
  import:
  certificates:
  run:

networks:
  ds:
    driver: bridge
    internal: true
  default:
```

The directory structure is simple:

project_folder
├─ structr
│    ├─... desired structr`s folders
│    └─ structr.conf
├─  neo4j
│    ├─ data
│    ├─ ...  
│    └─  Dockerfile / for run 
├─ frontend
├─  ...  
├─ docker-compose.yml
└─ .env
